"""add embeddings to document chunks

Revision ID: 0572aee2ae59
Revises: dfb994d3c451
Create Date: 2026-09-06 23:20:08.568875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '0572aee2ae59'
down_revision: Union[str, Sequence[str], None] = 'dfb994d3c451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'document_chunks',
        sa.Column(
            'embedding',
            Vector(1024),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
