"""replace chunk page number with page range

Revision ID: 4ebca102d6e8
Revises: 0572aee2ae59
Create Date: 2026-09-07 14:10:48.400510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebca102d6e8'
down_revision: Union[str, Sequence[str], None] = '0572aee2ae59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_start', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('page_end', sa.Integer(), nullable=True))
    op.drop_column('document_chunks', 'page_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('document_chunks', 'page_end')
    op.drop_column('document_chunks', 'page_start')
    # ### end Alembic commands ###
